name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Run this when you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: NODE_OPTIONS=--openssl-legacy-provider 

      - name: Lint code
        run: npm run lint --if-present

      - name: Build project
        run: CI=false npm run build


      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: 3.131.160.25      # <-- Replace with your EC2 Public IP
          USER: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r ./build $USER@$HOST:/var/www/myapp
          ssh -i key.pem $USER@$HOST "sudo systemctl restart nginx"
